language: java
jdk:
- oraclejdk8
before_install:
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
script:
- mvn clean install dockerfile:build dockerfile:push
before_deploy:
- openssl aes-256-cbc -K $encrypted_7fcd2402b693_key -iv $encrypted_7fcd2402b693_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 /tmp/deploy_rsa && ssh docker@52.187.120.141 '/usr/local/bin/docker-compose
    down && /usr/local/bin/docker-compose pull && /usr/local/bin/docker-compose up
    -d'
  on:
    branch: master
addons:
  ssh_known_hosts:
  - 52.187.120.141
env:
  global:
  - secure: NBd56L2gyvaXcGWxVzeNTvCskfmCVjId4ZAbLHtx/rxEvfmEomYxk9Mc1QD2PUrn9c3jaTpipw1NJICuyQmb3ILCPJla4K0OUmNx0Os0H2yZf/T464by9PpRhm2kOYqSTO1TJDn5x7KG/AsTqi+nzToic3BlsaQ3d4Y0ZfgS6SyMYbaayChaYZuWQX4Ia4Sl1cQB5xJ4q34aOP4SKVGmx1p9J7aG5Q3e/zpb2XaKpKLZGgV7Sq1NoPOH2YJ/CpwMglZOmvOGop3msdvf7lyBFQ04sjF0y3XjGHoPNV0XDpOpwm17PJheE8w03nMLOhgRSlpaGAgnfjYYPrdsgrqzybzseUBVe4sO6bmQ0YTRkhZaNNH0CAFnMm7CznAbw6ApNQxr+74yRHql4w/9kL2I/FzKqhdDx++mA4cWI3Ff7bzOzocVJjywB/TLBjsq09vi8CX2EH1nT4owyLcPFAOqhGwvTLUpfh1Fhf9qeL9/KULKpairv0k+q3xYzVDzbyrsuHi4/b0tgZqujM5IjRa4C0svntSJNeMLYYFqhqVTNhiCp0/vyqBUwh1lasRnWMFMeQBCeI3Q11YKIZG7np0sjHXBLfK5+7HGN8qZiMQV/OhYmv4cvzQWlTjYyYw2hG0oYeAKpr7w3qJyYZIUq/FcLYbNk9dD9wcbk3aMQWARGvY=
  - secure: vCIEgRboQg8vmPmg0Dxo9UbiPadsf8uV5Y4OPwk2xBUBS8KBNhDO2q4o6q4Bk8Tm+aO43lmUKvofjtxa4Vov6tmMz3MZvIzdIUvWCE3WcnNUh8HYk99LB6u5NiszuRaOLHGKshyKOocp2WAnJYFgbf17h7DmBi6JhbVZXLxg62kWTdCYHUsX42pulb0DiUhJo4sgtzaoYH0yLL/YHXkJiJfRNss3JkcuYKlGWdHfLz7tBHWZEETQa/TtMJogSuUiQj5+36jDFnOtj21ZDx0xGJLyNh038cDnZ0aMWv1D9O2Yk9+gIGjsSIAAj6SrTYTJlG0Zpeu0y6tNtPlJBMqA6x4sPCtZz+p46ceQ5U5BcwS+CEVKgrE2Eqh0NtYy2mFQKAhvzM+DBVJ19Bd4KO4YVOhD8oQrnueBn/aUJc1zN//keGEUG7t+yQPBCgJvbH/+eNv9O7+KXqMyIDx8hHHveCikJaMMYz+lBHnU3xWWrQJxZEEnf14LGrbi7GsTZ1rnMqR356SYkqlTFM5qcqT1MlUKrWvaO+rsRF23IV7mTTzgZDipxSKyIUz99Ht2HSlkhm+u+86OX3jJMkMn7fWH8H4iEcbRlTJ1pMEA/hcZcUgCok1N0/kmPLZ1AI9WaMJd0LplSvs6c7Hw6LJe16IZHFre7wPXUAKodOHjJ6WAszM=
  - secure: ioN8HeoAZ37d6HyUK50su/sEIwxVjqldYd5r25Sogbxuszk3RH0ob2S2g5SstYkl8RYG0sIedRuQkiu1CLjIFMqHVtc3tXV29P6XDmmgDz7B7YzXZGUw7r5Gv/hNNL/zHKcBEWfFsFqBiK28Dwmama6ECd8RS436iVPa5l3VvkU7TTuAog5XJe+CG+tNZUGX3XAh/30Y9zV41Jp9BHKRm+HPJL9kg7XMrutaSXNwa0T0wIWsbhIJTGW8vt4XIjepukUUXIyxotKES6v86v2YPWd8lFXKjoLGQUzIxntV6gXnD9obWsGNMyOsEfScnvHSP2NYMMyF7EDpsBwzn7T1ERV5x42+DfwnT5Lv4SVNC2bcuFDOIMMQmVkZnbmL1JUX5GtpIBzR2jrv3ZZuFX/F8PWPXKmZa4vetrKCHUASpCOXXzQwApOaC7M1e9wZyF90db65hNhJm8G1b0OuxV5K7uLqah1vltMZwQBV+18aZXwtkNu3CU2WgxQ+d36QgRkYMiqZdukx+ekDXFJGTgbCnCwEfgXaGVLGduKZlBlkyFSZB8ASKmBrzTfumetwZC46Z6rp7+yLnlyKf9vfaQ9vuts/Boq1LL5kysXL7RzOwxUHsTfZ0eChsuQ1FfxpxfCVnkdt3BLKwiXe4F+Lxqslt6G0zKf4/YKiyHFT3OW0ouk=
